# Generated by Django 5.1.3 on 2024-12-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_veteran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_veteran',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ssn',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
