# Generated by Django 5.1.3 on 2024-12-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_veteran_customuser_ssn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plaid_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
