# Generated by Django 5.1.3 on 2024-12-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
